### ISSUE TITLE
Responsive Çalışırken Cihazları Nasıl Test Ediyorsun?

### ISSUE THREAD

**Issue by aligoren** [dnomak/bana-istedigini-sor#17]
Selam, responsive tasarımlarda en popüler cihazlarda mümkün olan en iyi uyumluluğu hedefliyorsundur.

Bunu nasıl sağlıyorsun? iPhone'un 4,5,6 ve 7'si var. Samsung'un boyutları ayrı, LG'nin ayrı hepsi için ayrı ayrı mı yazıyorsun yoksa ayrı bir eklenti mi var?

Bir de media screenlerde sıralamanın bir önemi var mı? Örneğin şöyle:

```css
@media screen and (device-aspect-ratio: 2/3) {
    .bms-head-title {
        height: 5vh;
    }
}

@media screen and (device-aspect-ratio: 40/71) {
    .bms-head-title {
        height: 9vh;
    }
}
```

bu kodda ben iphone5 ve 6 için ayrı ayrı stiller vermek istiyorum acaba burada bir hata mı oluşuyor yoksa responsive tasarım bu yazdığımdan biraz daha mı farklı işliyor?

Çok fazla soru oldu ama front-end geliştirici alanında gitmeye çalışıyorum. JS konusunda uzman olmak isteyen birisi örnek @fatihacet gibi CSS konusunda ileri düzey bilgiye sahip olmalı mıdır? Yoksa dom'a müdahale edebiliyor ve nerede ne yapacağını biliyor ise yeterli midir?

Teşekkürler 😆
